# Generated by Django 4.0.6 on 2022-08-03 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'image'), ('2', 'video'), ('3', 'event')], max_length=1)),
                ('caption', models.CharField(blank=True, max_length=28)),
                ('description', models.TextField(blank=True, max_length=228)),
                ('tags', models.CharField(blank=True, max_length=228)),
                ('image_link', models.CharField(blank=True, max_length=228)),
                ('video_link', models.CharField(blank=True, max_length=228)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=28)),
                ('created_datetime', models.DateField(blank=True, null=True)),
                ('modified_datetime', models.DateField(blank=True, null=True)),
                ('deleted_datetime', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=28)),
                ('permission', models.CharField(blank=True, max_length=28)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('mobile', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=28)),
                ('address', models.TextField(blank=True, max_length=228)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'FeMale'), ('3', 'Other')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dp', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=228)),
                ('tags', models.CharField(blank=True, max_length=228)),
                ('image_link', models.CharField(blank=True, max_length=228)),
                ('created_datetime', models.DateField(blank=True, null=True)),
                ('modified_datetime', models.DateField(blank=True, null=True)),
                ('deleted_datetime', models.DateField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
